services:
  ubuntu-container:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
    volumes:
      - ./Terraform:/app/Terraform
    tty: true
    stdin_open: true
  
  app-container:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"